name: meldinger

networks:
  meldinger_network:
    name: meldinger_network

services:
  valkey:
    image: valkey/valkey:latest@sha256:475ee65cc75c327407458f5096cdd36954b3de3fc83f4c8ac31a4a8edecbf49e
    networks:
      - meldinger_network
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379

  postgres-receiver:
    image: postgres:17-alpine@sha256:18cfe3ef5e6815560c98237d6216d1e5119702fb0f3894c8785dd58b8bbe5d73
    networks:
      - meldinger_network
    ports:
      - 5432:5432
    volumes:
      - postgres-receiver-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  file-storage:
    container_name: file-storage
    image: fsouza/fake-gcs-server@sha256:797ce226d62f947c009dc40246b30cfb456b8473d8241407f9d6f2c04e4d69ef
    networks:
      - meldinger_network
    ports:
      - 4443:4443
    command:
      [
        "-scheme",
        "http",
        "-backend",
        "filesystem",
        "-external-url",
        "http://localhost:4443",
      ]
    volumes:
      - cloudstorage-data:/data
    post_start:
      - command: ["apk", "add", "--no-cache", "curl"]
      - command:
          [
            "curl",
            "-X",
            "POST",
            "-d",
            "{\"name\": \"test-bucket\",  \"location\":
              \"EU\",  \"storageClass\": \"STANDARD\",   \"iamConfiguration\":
              {  \"uniformBucketLevelAccess\": { \"enabled\": true} }}",
            "-H",
            "Content-Type: application/json",
            "http://localhost:4443/storage/v1/b?project=localhost",
          ]
      - command:
          [
            "curl",
            "-X",
            "PUT",
            "-d",
            "{\"externalUrl\": \"http://file-storage:4443\"}",
            "-H",
            "Content-Type: application/json",
            "http://file-storage:4443/_internal/config",
          ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4443/storage/v1/b/test-bucket"]
      interval: 1s
      timeout: 10s
      retries: 5

  clamav:
    image: clamav/clamav@sha256:f0954d679017eb6d48221e2b2be3ac5457bf278a844f39b672376f55a085f591
    environment:
      MODE: clamd
    networks:
      - meldinger_network
    profiles:
      - virus-scan
    ulimits:
      stack: 1048576
    volumes:
      - clamav-data:/var/lib/clamav
    ports:
      - "3310:3310"
    healthcheck:
      test: ["CMD-SHELL", "echo 'PING' | nc -w 5 localhost 3310"]
      interval: 1s
      timeout: 5s
      retries: 10

  clamav-web:
    image: europe-north1-docker.pkg.dev/nais-io/nais/images/clamav-rest:latest@sha256:8c6e3e36adf8f6c3770c15177a50f82053176a24b1db3aaae701630fe1ef4830
    container_name: clamav-web
    environment:
      DAEMON_ENDPOINT: clamav:3310
    ports:
      #http
      - "8091:8080"
    networks:
      - meldinger_network
    profiles:
      - virus-scan
    depends_on:
      clamav:
        condition: service_healthy

volumes:
  postgres-receiver-data:
  clamav-data:
  valkey-data:
  cloudstorage-data:
