name: meldinger

networks:
  meldinger_network:
    name: meldinger_network

services:
  valkey:
    image: valkey/valkey:latest@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
    networks:
      - meldinger_network
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379

  postgres-receiver:
    image: postgres:17-alpine@sha256:dc17045ccfd343b49600570ea734b9c4991cf1c3f3302e67df51e3b402dd55c4
    networks:
      - meldinger_network
    ports:
      - 5432:5432
    volumes:
      - postgres-receiver-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  file-storage:
    container_name: file-storage
    image: fsouza/fake-gcs-server@sha256:3730da0e31f7e5186a90ec4899dc2c336104e7599df400411392ef17e684c31f
    networks:
      - meldinger_network
    ports:
      - 4443:4443
    command:
      [
        "-scheme",
        "http",
        "-backend",
        "filesystem",
        "-external-url",
        "http://localhost:4443",
      ]
    volumes:
      - cloudstorage-data:/data
    post_start:
      - command: ["apk", "add", "--no-cache", "curl"]
      - command:
          [
            "curl",
            "-X",
            "POST",
            "-d",
            "{\"name\": \"test-bucket\",  \"location\":
              \"EU\",  \"storageClass\": \"STANDARD\",   \"iamConfiguration\":
              {  \"uniformBucketLevelAccess\": { \"enabled\": true} }}",
            "-H",
            "Content-Type: application/json",
            "http://localhost:4443/storage/v1/b?project=localhost",
          ]
      - command:
          [
            "curl",
            "-X",
            "PUT",
            "-d",
            "{\"externalUrl\": \"http://file-storage:4443\"}",
            "-H",
            "Content-Type: application/json",
            "http://file-storage:4443/_internal/config",
          ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4443/storage/v1/b/test-bucket"]
      interval: 1s
      timeout: 10s
      retries: 5

  clamav:
    image: clamav/clamav@sha256:c17762a00ba24dce4cf822fdc6f5bdfaa6e3ba152efc734d545b9a68be5641da
    environment:
      MODE: clamd
    networks:
      - meldinger_network
    profiles:
      - virus-scan
    ulimits:
      stack: 1048576
    volumes:
      - clamav-data:/var/lib/clamav
    ports:
      - "3310:3310"
    healthcheck:
      test: ["CMD-SHELL", "echo 'PING' | nc -w 5 localhost 3310"]
      interval: 1s
      timeout: 5s
      retries: 10

  clamav-web:
    image: europe-north1-docker.pkg.dev/nais-io/nais/images/clamav-rest:latest@sha256:1e59fe539ad8acb2acd98d313974f24737287cf3323be9c17ec15a26fbe3b3f5
    container_name: clamav-web
    environment:
      DAEMON_ENDPOINT: clamav:3310
    ports:
      #http
      - "8091:8080"
    networks:
      - meldinger_network
    profiles:
      - virus-scan
    depends_on:
      clamav:
        condition: service_healthy

volumes:
  postgres-receiver-data:
  clamav-data:
  valkey-data:
  cloudstorage-data:
