minimumReleaseAge: 4320

trustPolicy: no-downgrade

peerDependencyRules:
  allowedVersions:
    typescript: 6.0.3

overrides:
  js-yaml@<=4.1.1: ^4.1.2
  js-yaml@>=4.0.0 <4.3.0: ^5.0.0

minimumReleaseAgeExclude:
  - js-yaml@4.1.2 || 4.3.0
