name: meldinger

networks:
  meldinger_network:
    name: meldinger_network

services:
  valkey:
    image: valkey/valkey:latest@sha256:2bce660b767cb62c8c0ea020e94a230093be63dbd6af4f21b044960517a5842d
    networks:
      - meldinger_network
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379

  postgres-receiver:
    image: postgres:17-alpine@sha256:6f30057d31f5861b66f3545d4821f987aacf1dd920765f0acadea0c58ff975b1
    networks:
      - meldinger_network
    ports:
      - 5432:5432
    volumes:
      - postgres-receiver-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  file-storage:
    container_name: file-storage
    image: fsouza/fake-gcs-server@sha256:3730da0e31f7e5186a90ec4899dc2c336104e7599df400411392ef17e684c31f
    networks:
      - meldinger_network
    ports:
      - 4443:4443
    command: ["-scheme", "http", "-backend", "filesystem", "-external-url", "http://localhost:4443"]
    volumes:
      - cloudstorage-data:/data
    post_start:
      - command: ["apk", "add", "--no-cache", "curl"]
      - command:
          [
            "curl",
            "-X",
            "POST",
            "-d",
            "{\"name\": \"test-bucket\",  \"location\": \"EU\",  \"storageClass\": \"STANDARD\",   \"iamConfiguration\": {  \"uniformBucketLevelAccess\": { \"enabled\": true} }}",
            "-H",
            "Content-Type: application/json",
            "http://localhost:4443/storage/v1/b?project=localhost",
          ]
      - command:
          [
            "curl",
            "-X",
            "PUT",
            "-d",
            '{"externalUrl": "http://file-storage:4443"}',
            "-H",
            "Content-Type: application/json",
            "http://file-storage:4443/_internal/config",
          ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4443/storage/v1/b/test-bucket"]
      interval: 1s
      timeout: 10s
      retries: 5

  clamav:
    image: clamav/clamav@sha256:d772ad4aae0f7f2fb6fe7e7af570b5c4025ce9327d88ddba763fe015b02b564f
    environment:
      MODE: clamd
    networks:
      - meldinger_network
    ulimits:
      stack: 1048576
    volumes:
      - clamav-data:/var/lib/clamav
    ports:
      - "3310:3310"
    healthcheck:
      test: ["CMD-SHELL", "echo 'PING' | nc -w 5 localhost 3310"]
      interval: 1s
      timeout: 5s
      retries: 10

  clamav-web:
    image: europe-north1-docker.pkg.dev/nais-io/nais/images/clamav-rest:latest@sha256:f63d09769a15517e316e6d35379c66a144e6a5eaee37898ac6e9c56159e7dfda
    container_name: clamav-web
    environment:
      DAEMON_ENDPOINT: clamav:3310
    ports:
      #http
      - "8091:8080"
    networks:
      - meldinger_network
    depends_on:
      clamav:
        condition: service_healthy

volumes:
  postgres-receiver-data:
  clamav-data:
  valkey-data:
  cloudstorage-data:
